openapi: 3.0.0
info:
  title: PIX COBRANCA
  description: >-
    # Introdução

    APIS - pix cobrança


    # Documentação BACEN

    -  https://bacen.github.io/pix-api/index.html


    # Autenticação

    Padrão OAuth 2.


    - Basic Authentication para chamadas internas.

    - Client Credentials com mTLS para chamadas externas.


    # SWAGGER

    - SWAGGER OPENSHIFT SRP:
    https://srp-pix-srp.apps.ecpdsv.brb.com.br/swagger-ui/index.html


    # Rate limit

    50 requisições por segundo em cada cluster.


    # Timeouts

    Connect read: 5s

    Connect timeout: 2.5s
  version: 1.0.0
servers:
  - url: https://apidsv.brb.com.br
tags:
  - name: mTLS
  - name: PUBLICA
  - name: SQL INJECTION
  - name: COB
  - name: QRCODE
paths:
  /brb/v1/token:
    post:
      tags:
        - mTLS
      summary: TESTE - MTLS - v2 TOKEN
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  example: '{{client_id}}'
                client_secret:
                  type: string
                  example: '{{client_secret}}'
                grant_type:
                  type: string
                  example: client_credentials
                scope:
                  type: string
                  example: cob.read cob.write
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pix/v1/cobranca/cob:
    post:
      tags:
        - COB
      summary: Cob - PIX COBRANCA
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                devedor:
                  nome: Empresa de Serviços SA
                  cnpj: '12345678000195'
                valor:
                  original: '37.00'
                  modalidadeAlteracao: 1
                chave: 7d9f0335-8dcc-4054-9bf9-0dbd61d36906
                calendario:
                  expiracao: 3600
                infoAdicionais:
                  - valor: Informação Adicional1 do PSP-Recebedor
                    nome: Campo 1
                  - valor: Informação Adicional2 do PSP-Recebedor
                    nome: Campo 2
                solicitacaoPagador: Serviço realizado.
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Basic
            NTQ5NGM5MTctM2UxNi00ZmVmLThkNGUtMWYyNWNhYjg5YmZhOmMzNGM4YzMwLWRhMTItNDk5MC05MzhhLTg2MzM2NjliNDIyMw==
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pix/v1/cobranca/cob/f10856f357b74ab0976d092ab2b72268:
    get:
      tags:
        - COB
      summary: Cob - PIX COBRANCA
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Basic
            NTQ5NGM5MTctM2UxNi00ZmVmLThkNGUtMWYyNWNhYjg5YmZhOmMzNGM4YzMwLWRhMTItNDk5MC05MzhhLTg2MzM2NjliNDIyMw==
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pix/v1/cobranca/f10856f357b74ab0976d092ab2b72268:
    get:
      tags:
        - PUBLICA
      summary: CobPayload - PIX COBRANCA
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Basic
            NTQ5NGM5MTctM2UxNi00ZmVmLThkNGUtMWYyNWNhYjg5YmZhOmMzNGM4YzMwLWRhMTItNDk5MC05MzhhLTg2MzM2NjliNDIyMw==
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pix/v1/cobranca/id=' or '1'='1:
    get:
      tags:
        - SQL INJECTION
      summary: CobPayload - PIX COBRANCA SQL INJECTION
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Basic
            NTQ5NGM5MTctM2UxNi00ZmVmLThkNGUtMWYyNWNhYjg5YmZhOmMzNGM4YzMwLWRhMTItNDk5MC05MzhhLTg2MzM2NjliNDIyMw==
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pix/v1/cobranca/qrcode/imagem/base64/cob/{txid}:
    get:
      tags:
        - QRCODE
      summary: Cob QRCODE Base 64 - PIX COBRANCA
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Basic
            NTQ5NGM5MTctM2UxNi00ZmVmLThkNGUtMWYyNWNhYjg5YmZhOmMzNGM4YzMwLWRhMTItNDk5MC05MzhhLTg2MzM2NjliNDIyMw==
        - name: txid
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
